services:
  # Serviço principal da aplicação (gateway)
  app:
    build: .
    volumes:
      - .:/app
    # Expõe a porta 8080 do container para a porta 8080 do host
    ports:
      - "8080:8080"
    # Variáveis de ambiente para o container
    environment:
      # Configurações do banco de dados
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}  # Usuário do banco (lê do .env)
      - DB_PASSWORD=${DB_PASSWORD}  # Senha do banco (lê do .env)
      - DB_NAME=${DB_NAME}  # Nome do banco (lê do .env)
      # Configurações do Kafka
      - KAFKA_BROKER=kafka:9092
    # Espera esses serviços iniciarem primeiro
    depends_on:
      - postgres
      - kafka

  # Serviço do banco de dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    # Configurações do banco
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Verifica se o banco está pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Reinicia automaticamente se parar
    restart: unless-stopped

  # Serviço do Kafka
  kafka:
    # Imagem oficial do Kafka
    image: confluentinc/cp-server:7.9.0
    # Expõe a porta do Kafka
    ports:
      - "9092:9092"
    # Configurações do Kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    # Verifica se o Kafka está pronto
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:29092 --list
      interval: 30s
      timeout: 10s
      retries: 3
    # Reinicia automaticamente se parar
    restart: unless-stopped

  # Serviço para inicializar os tópicos do Kafka
  kafka-init:
    image: confluentinc/cp-server:7.9.0
    # Espera o Kafka estar saudável
    depends_on:
      kafka:
        condition: service_healthy
    # Comando para criar os tópicos necessários
    command: >
      bash -c "
        echo 'Iniciando criação dos tópicos...' &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic pending_transactions --partitions 1 --replication-factor 1 &&
        kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic transaction_results --partitions 1 --replication-factor 1 &&
        echo 'Tópicos criados com sucesso!'"

# Define os volumes para persistência
volumes:
  # Volume para persistir os dados do PostgreSQL
  postgres_data: